---
- hosts: vaultserver
  gather_facts: false
  vars:
    hey_install_target: "/usr/local/bin/hey"
  pre_tasks:
    - name: install required packages
      become: true
      package:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
      - curl
      - git
      - vim
      - jq
      - python3-apt
      - python3-pip
      - apt-transport-https
      - gnupg
      - unzip
      - software-properties-common
      register: task_result
      until: task_result is success
      retries: 3
      delay: 20
      changed_when: false

    - name: install hey
      become: true
      get_url:
        url: https://storage.googleapis.com/hey-release/hey_linux_amd64
        dest: '{{ hey_install_target }}'

    - name: change permissions of installer
      become: true
      file:
        path: '{{ hey_install_target }}'
        state: file
        mode: 0755

- hosts: vaultserver
  vars:
    machine_host: 'vaultserver'
  roles:
     - { role: docker, become: true }
     - role: minikube
       become: true
       environment:
         MINIKUBE_HOME: '{{ vagrant_home }}/.minikube'
         KUBECONFIG: '{{ vagrant_home }}/.kube/config'
     - { role: hostname, become: true }
     - role: vault
       environment:
         KUBECONFIG: '{{ vagrant_home }}/.kube/config'
     - role: consul
       environment:
         KUBECONFIG: '{{ vagrant_home }}/.kube/config'
